name: Run Tests 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run tests and collect coverage 
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt ./... 

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}